[package]
name = "dimensions"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
build = "build.rs"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
# cargo build --target wasm32-unknown-unknown --lib --release

[[bin]]
name = "dimensions"
path = "src/bin.rs"

[dependencies]
ndarray = "^0.11.2"

# I want something more like this:
#[target.cfg(not(wasm32-unknown-unknown)).dependencies]
# gegz's not compatible with wasm-unknown-unknown.
[target.'cfg(windows)'.dependencies]
ggez = "^0.4.2"

#[build-dependencies]
#cc = "1.0"

# WebGl.
#gl = "0.6.0"
#gl_generator = "0.5.0"
#wasm-bindgen = "0.2"
#cgmath = "0.16.1"
#quaternion = "0.3.0"
