[package]
name = "dimensions"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
build = "build.rs"

[dependencies]
ndarray = "0.11.2"
# piston2d-graphics = "0.26.0"
ggez = "0.4"
# cairo-rs = "0.4.1"