[package]
name = "dimensions"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.11.2"
ggez = "0.4.2"

# WebGl.
gl = "0.6.0"
gl_generator = "0.5.0"
wasm-bindgen = "0.2"
cgmath = "0.16.1"
quaternion = "0.3.0"
