[package]
name = "dimensions"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
build = "build.rs"

[dependencies]
ndarray = "0.11.2"
ggez = "0.4.2"
gfx = "0.17.1"
glutin = "0.12"
gfx_window_glutin = "0.20"