[package]
name = "dimensions"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
build = "build.rs"

[dependencies]
ndarray = "0.11.2"
ggez = "0.4.2"
# ndarray-linalg = { version = "0.9.0", features = ["openblas"] }